version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.62
    - 1.16.63
    - 1.17.0
    - 1.17.1
    - 1.17.10
    - 1.17.11
    - 1.17.12
    - 1.17.13
    - 1.17.14
    - 1.17.15
    - 1.17.16
    - 1.17.17
    - 1.17.18
    - 1.17.19
    - 1.17.2
    - 1.17.20
    - 1.17.21
    - 1.17.22
    - 1.17.23
    - 1.17.24
    - 1.17.25
    - 1.17.26
    - 1.17.27
    - 1.17.28
    - 1.17.29
    - 1.17.3
    - 1.17.30
    - 1.17.32
    - 1.17.33
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.38
    - 1.17.39
    - 1.17.4
    - 1.17.40
    - 1.17.43
    - 1.17.44
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.48
    - 1.17.49
    - 1.17.5
    - 1.17.50
    - 1.17.51
    - 1.17.52
    - 1.17.53
    - 1.17.54
    - 1.17.55
    - 1.17.56
    - 1.17.57
    - 1.17.58
    - 1.17.59
    - 1.17.6
    - 1.17.7
    - 1.17.8
    - 1.17.9
  - dependency-name: hypothesis
    versions:
    - 6.1.0
    - 6.1.1
    - 6.10.0
    - 6.2.0
    - 6.3.0
    - 6.3.1
    - 6.3.2
    - 6.3.3
    - 6.3.4
    - 6.4.0
    - 6.4.2
    - 6.4.3
    - 6.6.0
    - 6.7.0
    - 6.8.0
    - 6.8.1
    - 6.8.3
    - 6.8.4
    - 6.8.5
    - 6.8.7
    - 6.8.9
    - 6.9.1
    - 6.9.2
  - dependency-name: moto
    versions:
    - 1.3.17.dev228
    - 1.3.17.dev236
    - 1.3.17.dev240
    - 1.3.17.dev245
    - 1.3.17.dev246
    - 1.3.17.dev247
    - 1.3.17.dev251
    - 1.3.17.dev256
    - 1.3.17.dev264
    - 1.3.17.dev268
    - 1.3.17.dev272
    - 1.3.17.dev275
    - 1.3.17.dev280
    - 1.3.17.dev282
    - 1.3.17.dev283
    - 2.0.1
    - 2.0.1.dev286
    - 2.0.1.dev291
    - 2.0.1.dev293
    - 2.0.1.dev294
    - 2.0.1.dev295
    - 2.0.1.dev297
    - 2.0.2
    - 2.0.2.dev5
    - 2.0.2.dev7
    - 2.0.2.dev8
    - 2.0.3.dev10
    - 2.0.3.dev11
    - 2.0.3.dev19
    - 2.0.3.dev5
    - 2.0.3.dev6
    - 2.0.5
    - 2.0.5.dev10
    - 2.0.5.dev14
    - 2.0.5.dev15
    - 2.0.5.dev16
    - 2.0.5.dev6
    - 2.0.6.dev2
  - dependency-name: pytest-randomly
    versions:
    - 3.5.0
    - 3.6.0
  - dependency-name: pytest
    versions:
    - 6.2.2
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
