FROM python:3

RUN mkdir /cdflow
WORKDIR /cdflow

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY test_requirements.txt .
RUN pip install --no-cache-dir -r test_requirements.txt

COPY . .
